### ISSUE TITLE
Immediate hard crash on launch after connecting inconsistent wiimote, unable to reset

### ISSUE THREAD

**Issue by shuttah627** [Meowmaritus/WiitarThing#31]
Hi! I'm experiencing a new hard crash on startup where the window shows up white for about 3 seconds and then everything closes. 

The last thing I did with WiitarThing was connect a wiimote that was having a hard time recognizing a connected guitar. It was flashing between the wiimote icon and the guitar icon in the connected devices menu.

I was able to get an error log from the app, It reads as follows;

```
Object Reference not set to an instance of an object
   at WiinUSoft.MainWindow.Window_Loaded(Object sender, RoutedEventArgs e) in C:\Users\Meowmaritus\GitHub\WiitarThing\WiitarThing\Windows\MainWindow.xaml.cs:line 293
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at MS.Internal.LoadedOrUnloadedOperation.DoWork()
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
```

Has anyone else experienced this error? If so, how did you pass it? I'm straight up locked out of WiitarThing until I find a way to completely wipe the program from my computer (replacing the files with a fresh download of 2.7 did not clear the error) :(

**Comment by shuttah627** [comment]
Managed to capture what was going on before the whole application stopped opening anymore, on a different PC. Constant flickering between wiimote mode and guitar mode, the fake xbox controller drops in and out of existance just as fast, and for some reason the up arrow keeps getting hit (?)
![connectdisconnect](https://github.com/user-attachments/assets/1c2314aa-9ae1-4baf-a18f-d5370a207f0c)
